import type { Metadata } from 'next';
import './globals.css';
import styles from './RootLayout.module.css';
import Footer from './components/LumiFooter';
import Image from 'next/image';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <main className={styles.layout}>
          <Image
            src='/white-logo.png'
            alt='Face Institute Logo'
            width={215}
            height={69}
          />
          <div className={styles.intro}>
            <p>AI Assistant</p>
          </div>
          {children}
          <Footer />
        </main>
      </body>
    </html>
  );
}
